// @generated
// This file is @generated by prost-build.
/// Set operations
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SetRequest {
    #[prost(string, tag="1")]
    pub key: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="2")]
    pub value: ::prost::alloc::vec::Vec<u8>,
}
/// Empty - uses gRPC status codes
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SetResponse {
}
/// Get operations
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetRequest {
    #[prost(string, tag="1")]
    pub key: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetResponse {
    #[prost(bytes="vec", tag="1")]
    pub value: ::prost::alloc::vec::Vec<u8>,
}
/// Delete operations
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteRequest {
    #[prost(string, tag="1")]
    pub key: ::prost::alloc::string::String,
}
/// Empty - uses gRPC status codes
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteResponse {
}
/// Flush operations
///
/// Empty - uses gRPC status codes
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FlushRequest {
}
/// Empty - uses gRPC status codes
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FlushResponse {
}
/// Keys operations
///
/// Empty - uses gRPC status codes
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct KeysRequest {
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct KeysResponse {
    #[prost(string, repeated, tag="1")]
    pub keys: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
include!("nanodb.tonic.rs");
// @@protoc_insertion_point(module)
